
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ContentWrapper from '../components/wrapper/content'
import NavbarComponent from '@/components/navbar-component'
import ClientWrapper from '@/components/wrapper/client'
import RightDrawer from '@/components/right-drawer-component'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <ClientWrapper>
          <RightDrawer />
        </ClientWrapper>
        <ClientWrapper>
          <NavbarComponent />
        </ClientWrapper>
        <ContentWrapper>
          {children}
        </ContentWrapper>
      </body>
    </html>
  )
}
